"""Build a small, link-only Markdown catalog from the canonical paper labels.

The private warehouse remains the source of truth. This module deliberately
does not export abstracts, downloaded files, or raw API responses.
"""

from __future__ import annotations

import re
from collections import defaultdict
from html import unescape
from pathlib import Path
from urllib.parse import quote, urlsplit, urlunsplit

from .api import Client
from .api.models import PaperRecord


GENERATED_MARKER = "<!-- Generated by field_cartography.public_catalog; do not edit. -->"
CATEGORIES = {
    "fmri_gnn": ("Graph and geometric deep learning", "fmri_gnn.md"),
    "fmri_geometric_manifold": ("Geometric, manifold, and topological methods", "fmri_geometric_manifold.md"),
    "fmri_graph_classical": ("Classical graph analysis", "fmri_graph_classical.md"),
}

SOURCE_GROUPS = {
    "doi": ("DOI", "doi.md"),
    "arxiv": ("arXiv", "arxiv.md"),
    "pubmed": ("PubMed or PMC", "pubmed-pmc.md"),
    "other": ("Other stable source", "other.md"),
    "pending": ("Source link pending", "pending.md"),
}


def _clean_text(value: object) -> str:
    """Keep untrusted paper metadata on a single, literal Markdown line."""
    text = re.sub(r"</?[A-Za-z][^>]*>", "", str(value or ""))
    text = re.sub(r"\s+", " ", unescape(text)).strip()
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    for char in ("\\", "[", "]", "*", "_", "`"):
        text = text.replace(char, "\\" + char)
    return text


def _valid_identifier(value: str | None) -> str | None:
    if not value:
        return None
    value = value.strip()
    return value if re.fullmatch(r"[A-Za-z0-9._/;()-]+", value) else None


def source_links(paper: PaperRecord) -> list[str]:
    """Return stable source links; never emit local files or signed PDF URLs."""
    identifiers = paper.external_ids
    links: list[str] = []
    doi = identifiers.doi
    if not doi and paper.canonical_id.lower().startswith("doi:"):
        doi = paper.canonical_id[4:]
    if doi:
        doi = re.sub(r"^(?:https?://doi\.org/|doi:)", "", doi.strip(), flags=re.I)
    doi = _valid_identifier(doi)
    if doi:
        links.append(f"[DOI](https://doi.org/{quote(doi, safe='/')})")

    arxiv = identifiers.arxiv
    if not arxiv and doi:
        match = re.fullmatch(r"10\.48550/arxiv\.(.+)", doi, flags=re.I)
        if match:
            arxiv = match.group(1)
    if not arxiv and paper.canonical_id.lower().startswith("arxiv:"):
        arxiv = paper.canonical_id[6:]
    arxiv = _valid_identifier(arxiv)
    if arxiv:
        links.append(f"[arXiv](https://arxiv.org/abs/{quote(arxiv, safe='/')})")

    pmc = re.sub(r"^PMC", "", str(identifiers.pmc or ""), flags=re.I)
    if pmc.isdigit():
        links.append(f"[PMC](https://pmc.ncbi.nlm.nih.gov/articles/PMC{pmc}/)")
    pubmed = str(identifiers.pubmed or "")
    if pubmed.isdigit():
        links.append(f"[PubMed](https://pubmed.ncbi.nlm.nih.gov/{pubmed}/)")

    # The warehouse's open-access URL is a link to the source, not a file we
    # redistribute. Omit signed/parameterized links, which expire or may leak
    # access credentials into the public catalog.
    if paper.open_access_pdf_url:
        parsed = urlsplit(paper.open_access_pdf_url)
        host = (parsed.hostname or "").lower()
        if (
            parsed.scheme in {"http", "https"}
            and host
            and re.fullmatch(r"[a-z0-9.-]+", host)
            and not parsed.username
            and not parsed.password
            and not parsed.query
            and not parsed.fragment
        ):
            safe_path = quote(parsed.path, safe="/%:@+,-._~")
            url = urlunsplit((parsed.scheme, parsed.netloc, safe_path, "", ""))
            duplicates_known_source = (
                (doi and host in {"doi.org", "dx.doi.org"})
                or (arxiv and host in {"arxiv.org", "www.arxiv.org"})
                or (pmc and host in {"ncbi.nlm.nih.gov", "www.ncbi.nlm.nih.gov", "pmc.ncbi.nlm.nih.gov"})
            )
            if not duplicates_known_source:
                links.append(f"[Source: {host}]({url})")
    return links


def collect_papers(client: Client) -> dict[str, list[PaperRecord]]:
    """Use the client's alias-aware, tier-aware classification reducer."""
    result: dict[str, list[PaperRecord]] = {}
    for category in CATEGORIES:
        identifiers = sorted(client.papers_in_category(category))
        records = client.metadata_batch(identifiers)
        result[category] = [
            paper
            for paper in records.values()
            if paper.category == category and paper.title and paper.title.strip()
        ]
    return result


def _sort_key(paper: PaperRecord) -> tuple[bool, int, str, str]:
    year = paper.year if isinstance(paper.year, int) else None
    return (year is None, -(year or 0), paper.title.casefold(), paper.canonical_id)


def _paper_line(paper: PaperRecord, *, include_venue: bool = True) -> str:
    title = _clean_text(paper.title)
    venue = _clean_text(paper.venue) if include_venue else ""
    suffix = f" — {venue}" if venue else ""
    links = source_links(paper)
    links_text = " · ".join(links) if links else "Source link pending"
    description = f"{title}{suffix}"
    punctuation = "" if description.endswith((".", "?", "!")) else "."
    return f"- {description}{punctuation} {links_text}"


def _all_papers(groups: dict[str, list[PaperRecord]]) -> list[PaperRecord]:
    return [paper for category in CATEGORIES for paper in groups.get(category, [])]


def render_category(category: str, papers: list[PaperRecord]) -> str:
    heading, _ = CATEGORIES[category]
    lines = [
        GENERATED_MARKER,
        f"# {heading}",
        "",
        "[← Catalog home](README.md)",
        "",
        f"{len(papers):,} papers. Sorted by year, then title.",
        "",
    ]
    years: dict[int | None, list[PaperRecord]] = defaultdict(list)
    for paper in sorted(papers, key=_sort_key):
        years[paper.year if isinstance(paper.year, int) else None].append(paper)
    for year, group in years.items():
        lines.extend([f"## {year if year is not None else 'Year unknown'}", ""])
        for paper in group:
            lines.append(_paper_line(paper))
        lines.append("")
    return "\n".join(lines)


def _year_slug(year: int | None) -> str:
    return f"{year}.md" if year is not None else "unknown.md"


def render_year_index(groups: dict[str, list[PaperRecord]]) -> str:
    by_year: dict[int | None, list[PaperRecord]] = defaultdict(list)
    for paper in _all_papers(groups):
        by_year[paper.year if isinstance(paper.year, int) else None].append(paper)
    ordered = sorted((year for year in by_year if year is not None), reverse=True)
    if None in by_year:
        ordered.append(None)
    lines = [
        GENERATED_MARKER,
        "# Browse by publication year",
        "",
        "[← Catalog home](../README.md)",
        "",
        "Each paper appears once, under its recorded publication year.",
        "",
        "| Year | All | Deep learning | Geometric / topology | Classical graph |",
        "|---|---:|---:|---:|---:|",
    ]
    for year in ordered:
        rows = by_year[year]
        counts = defaultdict(int)
        for paper in rows:
            counts[paper.category] += 1
        label = str(year) if year is not None else "Unknown"
        lines.append(
            f"| [{label}]({_year_slug(year)}) | {len(rows):,} | "
            f"{counts['fmri_gnn']:,} | {counts['fmri_geometric_manifold']:,} | "
            f"{counts['fmri_graph_classical']:,} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_year_page(year: int | None, papers: list[PaperRecord]) -> str:
    label = str(year) if year is not None else "Year unknown"
    lines = [
        GENERATED_MARKER,
        f"# {label}",
        "",
        "[← All years](README.md) · [Catalog home](../README.md)",
        "",
        f"{len(papers):,} papers.",
        "",
    ]
    for category, (heading, _) in CATEGORIES.items():
        category_papers = sorted(
            (paper for paper in papers if paper.category == category), key=_sort_key
        )
        if not category_papers:
            continue
        lines.extend([f"## {heading} ({len(category_papers):,})", ""])
        lines.extend(_paper_line(paper) for paper in category_papers)
        lines.append("")
    return "\n".join(lines)


def _venue_name(paper: PaperRecord) -> str:
    return re.sub(r"\s+", " ", (paper.venue or "").strip()) or "Unknown venue"


def _venue_bucket(venue: str) -> str:
    if venue == "Unknown venue":
        return "unknown"
    first = venue[0].upper()
    if "A" <= first <= "Z":
        return first.lower()
    if first.isdigit():
        return "0-9"
    return "other"


def _venue_bucket_label(bucket: str) -> str:
    if len(bucket) == 1:
        return bucket.upper()
    return {"0-9": "0–9 / symbols", "other": "Other", "unknown": "Unknown"}[bucket]


def render_venue_index(groups: dict[str, list[PaperRecord]]) -> str:
    bucket_venues: dict[str, set[str]] = defaultdict(set)
    bucket_papers: dict[str, int] = defaultdict(int)
    for paper in _all_papers(groups):
        venue = _venue_name(paper)
        bucket = _venue_bucket(venue)
        bucket_venues[bucket].add(venue)
        bucket_papers[bucket] += 1
    order = [chr(code) for code in range(ord("a"), ord("z") + 1)] + ["0-9", "other", "unknown"]
    lines = [
        GENERATED_MARKER,
        "# Browse by publication venue",
        "",
        "[← Catalog home](../README.md)",
        "",
        "Venues are grouped alphabetically so the catalog stays compact.",
        "",
        "| Group | Venues | Papers |",
        "|---|---:|---:|",
    ]
    for bucket in order:
        if not bucket_papers[bucket]:
            continue
        label = _venue_bucket_label(bucket)
        lines.append(
            f"| [{label}]({bucket}.md) | {len(bucket_venues[bucket]):,} | "
            f"{bucket_papers[bucket]:,} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_venue_page(bucket: str, papers: list[PaperRecord]) -> str:
    title = _venue_bucket_label(bucket)
    venues: dict[str, list[PaperRecord]] = defaultdict(list)
    for paper in papers:
        venues[_venue_name(paper)].append(paper)
    lines = [
        GENERATED_MARKER,
        f"# Publication venues: {title}",
        "",
        "[← All venue groups](README.md) · [Catalog home](../README.md)",
        "",
        f"{len(venues):,} venues and {len(papers):,} papers.",
        "",
    ]
    for venue in sorted(venues, key=str.casefold):
        venue_papers = sorted(venues[venue], key=_sort_key)
        lines.extend([f"## {_clean_text(venue)} ({len(venue_papers):,})", ""])
        lines.extend(_paper_line(paper, include_venue=False) for paper in venue_papers)
        lines.append("")
    return "\n".join(lines)


def _source_group(paper: PaperRecord) -> str:
    links = source_links(paper)
    if any(link.startswith("[DOI]") for link in links):
        return "doi"
    if any(link.startswith("[arXiv]") for link in links):
        return "arxiv"
    if any(link.startswith(("[PubMed]", "[PMC]")) for link in links):
        return "pubmed"
    return "other" if links else "pending"


def render_source_index(groups: dict[str, list[PaperRecord]]) -> str:
    counts = defaultdict(int)
    for paper in _all_papers(groups):
        counts[_source_group(paper)] += 1
    lines = [
        GENERATED_MARKER,
        "# Browse by source link",
        "",
        "[← Catalog home](../README.md)",
        "",
        "Each paper is assigned to its best available stable source link.",
        "",
        "| Source | Papers |",
        "|---|---:|",
    ]
    for group, (label, filename) in SOURCE_GROUPS.items():
        lines.append(f"| [{label}]({filename}) | {counts[group]:,} |")
    lines.append("")
    return "\n".join(lines)


def render_source_page(group: str, papers: list[PaperRecord]) -> str:
    label, _ = SOURCE_GROUPS[group]
    lines = [
        GENERATED_MARKER,
        f"# Source: {label}",
        "",
        "[← Source groups](README.md) · [Catalog home](../README.md)",
        "",
        f"{len(papers):,} papers.",
        "",
    ]
    years: dict[int | None, list[PaperRecord]] = defaultdict(list)
    for paper in sorted(papers, key=_sort_key):
        years[paper.year if isinstance(paper.year, int) else None].append(paper)
    for year, year_papers in years.items():
        lines.extend([f"## {year if year is not None else 'Year unknown'}", ""])
        lines.extend(_paper_line(paper) for paper in year_papers)
        lines.append("")
    return "\n".join(lines)


def render_index(groups: dict[str, list[PaperRecord]]) -> str:
    lines = [
        GENERATED_MARKER,
        "# fMRI Graph Library: paper catalog",
        "",
        "A link-only catalog generated from the private research warehouse.",
        "No article PDF, converted full text, abstract, or raw API response is included.",
        "Classification is machine-assisted and does not mean every entry has been manually verified.",
        "",
        "## Browse",
        "",
        "| View | Description |",
        "|---|---|",
        "| [By method](#browse-by-method) | Three methodological families |",
        "| [By publication year](by_year/README.md) | Year pages with method breakdowns |",
        "| [By publication venue](by_venue/README.md) | Alphabetical venue groups |",
        "| [By source link](by_source/README.md) | DOI, arXiv, PubMed/PMC, other, or pending |",
        "",
        "## Browse by method",
        "",
        "| Category | Papers |",
        "|---|---:|",
    ]
    for category, (heading, filename) in CATEGORIES.items():
        lines.append(f"| [{heading}]({filename}) | {len(groups[category]):,} |")
    lines.extend([
        "",
        "The classical graph-analysis category is adjacent to, but not identical with,",
        "graph *learning*. It is retained separately for transparent scope decisions.",
        "The private warehouse stores the citation network and downloaded texts;",
        "these pages provide bibliographic links only.",
        "",
    ])
    return "\n".join(lines)


def _write_generated(path: Path, content: str) -> None:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
        raise FileExistsError(f"refusing to overwrite a hand-edited file: {path}")
    path.write_text(content, encoding="utf-8")


def _sync_generated_directory(path: Path, pages: dict[str, str]) -> None:
    if path.exists():
        for existing in path.glob("*.md"):
            if not existing.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                raise FileExistsError(f"refusing to remove a hand-edited file: {existing}")
        for existing in path.glob("*.md"):
            existing.unlink()
    path.mkdir(parents=True, exist_ok=True)
    for filename, content in pages.items():
        _write_generated(path / filename, content)


def build_catalog(client: Client, output_dir: Path) -> dict[str, int]:
    groups = collect_papers(client)
    papers = _all_papers(groups)
    # Check all destinations before writing any file.
    targets = [output_dir / "README.md"] + [
        output_dir / filename for _, filename in CATEGORIES.values()
    ]
    for path in targets:
        if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            raise FileExistsError(f"refusing to overwrite a hand-edited file: {path}")
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_generated(output_dir / "README.md", render_index(groups))
    for category, (_, filename) in CATEGORIES.items():
        _write_generated(output_dir / filename, render_category(category, groups[category]))

    by_year: dict[int | None, list[PaperRecord]] = defaultdict(list)
    by_venue_bucket: dict[str, list[PaperRecord]] = defaultdict(list)
    by_source: dict[str, list[PaperRecord]] = defaultdict(list)
    for paper in papers:
        year = paper.year if isinstance(paper.year, int) else None
        by_year[year].append(paper)
        by_venue_bucket[_venue_bucket(_venue_name(paper))].append(paper)
        by_source[_source_group(paper)].append(paper)

    year_pages = {"README.md": render_year_index(groups)}
    year_pages.update({
        _year_slug(year): render_year_page(year, year_papers)
        for year, year_papers in by_year.items()
    })
    _sync_generated_directory(output_dir / "by_year", year_pages)

    venue_pages = {"README.md": render_venue_index(groups)}
    venue_pages.update({
        f"{bucket}.md": render_venue_page(bucket, venue_papers)
        for bucket, venue_papers in by_venue_bucket.items()
    })
    _sync_generated_directory(output_dir / "by_venue", venue_pages)

    source_pages = {"README.md": render_source_index(groups)}
    source_pages.update({
        filename: render_source_page(group, by_source.get(group, []))
        for group, (_, filename) in SOURCE_GROUPS.items()
    })
    _sync_generated_directory(output_dir / "by_source", source_pages)
    return {category: len(groups[category]) for category in CATEGORIES}
