"""Build a small, link-only Markdown catalog from the canonical paper labels.

The private warehouse remains the source of truth. This module deliberately
does not export abstracts, downloaded files, or raw API responses.
"""

from __future__ import annotations

import re
from collections import defaultdict
from html import unescape
from pathlib import Path
from urllib.parse import quote, urlsplit, urlunsplit

from .api import Client
from .api.models import PaperRecord


GENERATED_MARKER = "<!-- Generated by field_cartography.public_catalog; do not edit. -->"
CATEGORIES = {
    "fmri_gnn": ("Graph and geometric deep learning", "fmri_gnn.md"),
    "fmri_geometric_manifold": ("Geometric, manifold, and topological methods", "fmri_geometric_manifold.md"),
    "fmri_graph_classical": ("Classical graph analysis", "fmri_graph_classical.md"),
}


def _clean_text(value: object) -> str:
    """Keep untrusted paper metadata on a single, literal Markdown line."""
    text = re.sub(r"</?[A-Za-z][^>]*>", "", str(value or ""))
    text = re.sub(r"\s+", " ", unescape(text)).strip()
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    for char in ("\\", "[", "]", "*", "_", "`"):
        text = text.replace(char, "\\" + char)
    return text


def _valid_identifier(value: str | None) -> str | None:
    if not value:
        return None
    value = value.strip()
    return value if re.fullmatch(r"[A-Za-z0-9._/;()-]+", value) else None


def source_links(paper: PaperRecord) -> list[str]:
    """Return stable source links; never emit local files or signed PDF URLs."""
    identifiers = paper.external_ids
    links: list[str] = []
    doi = identifiers.doi
    if not doi and paper.canonical_id.lower().startswith("doi:"):
        doi = paper.canonical_id[4:]
    if doi:
        doi = re.sub(r"^(?:https?://doi\.org/|doi:)", "", doi.strip(), flags=re.I)
    doi = _valid_identifier(doi)
    if doi:
        links.append(f"[DOI](https://doi.org/{quote(doi, safe='/')})")

    arxiv = identifiers.arxiv
    if not arxiv and doi:
        match = re.fullmatch(r"10\.48550/arxiv\.(.+)", doi, flags=re.I)
        if match:
            arxiv = match.group(1)
    if not arxiv and paper.canonical_id.lower().startswith("arxiv:"):
        arxiv = paper.canonical_id[6:]
    arxiv = _valid_identifier(arxiv)
    if arxiv:
        links.append(f"[arXiv](https://arxiv.org/abs/{quote(arxiv, safe='/')})")

    pmc = re.sub(r"^PMC", "", str(identifiers.pmc or ""), flags=re.I)
    if pmc.isdigit():
        links.append(f"[PMC](https://pmc.ncbi.nlm.nih.gov/articles/PMC{pmc}/)")
    pubmed = str(identifiers.pubmed or "")
    if pubmed.isdigit():
        links.append(f"[PubMed](https://pubmed.ncbi.nlm.nih.gov/{pubmed}/)")

    # The warehouse's open-access URL is a link to the source, not a file we
    # redistribute. Omit signed/parameterized links, which expire or may leak
    # access credentials into the public catalog.
    if paper.open_access_pdf_url:
        parsed = urlsplit(paper.open_access_pdf_url)
        host = (parsed.hostname or "").lower()
        if (
            parsed.scheme in {"http", "https"}
            and host
            and re.fullmatch(r"[a-z0-9.-]+", host)
            and not parsed.username
            and not parsed.password
            and not parsed.query
            and not parsed.fragment
        ):
            safe_path = quote(parsed.path, safe="/%:@+,-._~")
            url = urlunsplit((parsed.scheme, parsed.netloc, safe_path, "", ""))
            duplicates_known_source = (
                (doi and host in {"doi.org", "dx.doi.org"})
                or (arxiv and host in {"arxiv.org", "www.arxiv.org"})
                or (pmc and host in {"ncbi.nlm.nih.gov", "www.ncbi.nlm.nih.gov", "pmc.ncbi.nlm.nih.gov"})
            )
            if not duplicates_known_source:
                links.append(f"[Source: {host}]({url})")
    return links


def collect_papers(client: Client) -> dict[str, list[PaperRecord]]:
    """Use the client's alias-aware, tier-aware classification reducer."""
    result: dict[str, list[PaperRecord]] = {}
    for category in CATEGORIES:
        identifiers = sorted(client.papers_in_category(category))
        records = client.metadata_batch(identifiers)
        result[category] = [
            paper
            for paper in records.values()
            if paper.category == category and paper.title and paper.title.strip()
        ]
    return result


def _sort_key(paper: PaperRecord) -> tuple[bool, int, str, str]:
    year = paper.year if isinstance(paper.year, int) else None
    return (year is None, -(year or 0), paper.title.casefold(), paper.canonical_id)


def render_category(category: str, papers: list[PaperRecord]) -> str:
    heading, _ = CATEGORIES[category]
    lines = [GENERATED_MARKER, f"# {heading}", "", f"{len(papers):,} papers. Sorted by year, then title.", ""]
    years: dict[int | None, list[PaperRecord]] = defaultdict(list)
    for paper in sorted(papers, key=_sort_key):
        years[paper.year if isinstance(paper.year, int) else None].append(paper)
    for year, group in years.items():
        lines.extend([f"## {year if year is not None else 'Year unknown'}", ""])
        for paper in group:
            title = _clean_text(paper.title)
            venue = _clean_text(paper.venue)
            suffix = f" — {venue}" if venue else ""
            links = source_links(paper)
            links_text = " · ".join(links) if links else "Source link pending"
            description = f"{title}{suffix}"
            punctuation = "" if description.endswith((".", "?", "!")) else "."
            lines.append(f"- {description}{punctuation} {links_text}")
        lines.append("")
    return "\n".join(lines)


def render_index(groups: dict[str, list[PaperRecord]]) -> str:
    lines = [
        GENERATED_MARKER,
        "# fMRI Graph Library: paper catalog",
        "",
        "A link-only catalog generated from the private research warehouse.",
        "No article PDF, converted full text, abstract, or raw API response is included.",
        "Classification is machine-assisted and does not mean every entry has been manually verified.",
        "",
        "| Category | Papers |",
        "|---|---:|",
    ]
    for category, (heading, filename) in CATEGORIES.items():
        lines.append(f"| [{heading}]({filename}) | {len(groups[category]):,} |")
    lines.extend([
        "",
        "The classical graph-analysis category is adjacent to, but not identical with,",
        "graph *learning*. It is retained separately for transparent scope decisions.",
        "The private warehouse stores the citation network and downloaded texts;",
        "these pages provide bibliographic links only.",
        "",
    ])
    return "\n".join(lines)


def _write_generated(path: Path, content: str) -> None:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
        raise FileExistsError(f"refusing to overwrite a hand-edited file: {path}")
    path.write_text(content, encoding="utf-8")


def build_catalog(client: Client, output_dir: Path) -> dict[str, int]:
    groups = collect_papers(client)
    # Check all destinations before writing any file.
    targets = [output_dir / "README.md"] + [
        output_dir / filename for _, filename in CATEGORIES.values()
    ]
    for path in targets:
        if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            raise FileExistsError(f"refusing to overwrite a hand-edited file: {path}")
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_generated(output_dir / "README.md", render_index(groups))
    for category, (_, filename) in CATEGORIES.items():
        _write_generated(output_dir / filename, render_category(category, groups[category]))
    return {category: len(groups[category]) for category in CATEGORIES}
