"""Build a publication-safe graph induced by the public paper catalog."""

from __future__ import annotations

import csv
import hashlib
import json
import xml.etree.ElementTree as ET
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from .api import Client
from .api.models import PaperRecord
from .public_catalog import CATEGORIES, collect_papers


GENERATED_MARKER = "<!-- Generated by field_cartography.public_graph; do not edit. -->"


def _external_id(paper: PaperRecord, name: str) -> str:
    value = getattr(paper.external_ids, name, None)
    if value:
        return str(value)
    prefix = f"{name}:"
    if paper.canonical_id.lower().startswith(prefix):
        return paper.canonical_id[len(prefix):]
    return ""


def _read_induced_edges(edge_path: Path, node_ids: set[str]) -> tuple[list[tuple[str, str]], int]:
    """Return unique, directed catalog-to-catalog citations and removed self-loop count."""
    edges: set[tuple[str, str]] = set()
    self_loops = 0
    with edge_path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            record = json.loads(line)
            source = record.get("from")
            target = record.get("to")
            if source not in node_ids or target not in node_ids:
                continue
            if source == target:
                self_loops += 1
                continue
            edges.add((source, target))
    return sorted(edges), self_loops


def _component_stats(node_ids: set[str], edges: Iterable[tuple[str, str]]) -> dict[str, int]:
    adjacency = {node_id: set() for node_id in node_ids}
    for source, target in edges:
        adjacency[source].add(target)
        adjacency[target].add(source)
    visited: set[str] = set()
    sizes: list[int] = []
    for start in sorted(node_ids):
        if start in visited:
            continue
        stack = [start]
        size = 0
        while stack:
            node_id = stack.pop()
            if node_id in visited:
                continue
            visited.add(node_id)
            size += 1
            stack.extend(adjacency[node_id] - visited)
        sizes.append(size)
    sizes.sort(reverse=True)
    return {
        "total": len(sizes),
        "largest": sizes[0] if sizes else 0,
        "isolated": sum(size == 1 for size in sizes),
    }


def _write_nodes_csv(path: Path, papers: list[PaperRecord]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow([
            "paper_id",
            "title",
            "year",
            "venue",
            "category",
            "doi",
            "arxiv",
            "pubmed",
            "pmc",
            "citation_count",
        ])
        for paper in papers:
            writer.writerow([
                paper.canonical_id,
                paper.title or "",
                paper.year or "",
                paper.venue or "",
                paper.category or "",
                _external_id(paper, "doi"),
                _external_id(paper, "arxiv"),
                _external_id(paper, "pubmed"),
                _external_id(paper, "pmc"),
                paper.citation_count if paper.citation_count is not None else "",
            ])


def _write_edges_csv(path: Path, edges: list[tuple[str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["source", "target", "relation"])
        for source, target in edges:
            writer.writerow([source, target, "cites"])


def _add_data(parent: ET.Element, key: str, value: Any) -> None:
    if value is None or value == "":
        return
    element = ET.SubElement(parent, "data", key=key)
    element.text = str(value)


def _write_graphml(path: Path, papers: list[PaperRecord], edges: list[tuple[str, str]]) -> None:
    namespace = "http://graphml.graphstruct.org/xmlns"
    ET.register_namespace("", namespace)
    graphml = ET.Element("graphml", xmlns=namespace)
    attributes = [
        ("title", "string"),
        ("year", "int"),
        ("venue", "string"),
        ("category", "string"),
        ("doi", "string"),
        ("arxiv", "string"),
        ("pubmed", "string"),
        ("pmc", "string"),
        ("citation_count", "int"),
    ]
    for name, kind in attributes:
        ET.SubElement(
            graphml,
            "key",
            {"id": name, "for": "node", "attr.name": name, "attr.type": kind},
        )
    ET.SubElement(
        graphml,
        "key",
        {"id": "relation", "for": "edge", "attr.name": "relation", "attr.type": "string"},
    )
    graph = ET.SubElement(graphml, "graph", edgedefault="directed")
    for paper in papers:
        node = ET.SubElement(graph, "node", id=paper.canonical_id)
        _add_data(node, "title", paper.title)
        _add_data(node, "year", paper.year)
        _add_data(node, "venue", paper.venue)
        _add_data(node, "category", paper.category)
        for name in ("doi", "arxiv", "pubmed", "pmc"):
            _add_data(node, name, _external_id(paper, name))
        _add_data(node, "citation_count", paper.citation_count)
    for index, (source, target) in enumerate(edges):
        edge = ET.SubElement(
            graph,
            "edge",
            {"id": f"e{index}", "source": source, "target": target},
        )
        _add_data(edge, "relation", "cites")
    tree = ET.ElementTree(graphml)
    ET.indent(tree, space="  ")
    tree.write(path, encoding="utf-8", xml_declaration=True)


def _render_readme(version: str, stats: dict[str, Any]) -> str:
    return "\n".join([
        GENERATED_MARKER,
        f"# fMRI Graph Library — public graph {version}",
        "",
        "[← Paper catalog](../../public_catalog/README.md)",
        "",
        "This is the directed citation graph induced by the public paper catalog.",
        "Its node set is exactly the catalog: no external citation-neighborhood",
        "papers are included. Catalog papers without an internal citation edge are",
        "retained as isolated nodes.",
        "",
        "## Snapshot",
        "",
        f"- Nodes: **{stats['nodes']:,}**",
        f"- Directed citation edges: **{stats['edges']:,}**",
        f"- Isolated nodes: **{stats['components']['isolated']:,}**",
        f"- Largest weakly connected component: **{stats['components']['largest']:,} nodes**",
        f"- Self-loops removed: **{stats['self_loops_removed']:,}**",
        "",
        "## Files",
        "",
        "- `nodes.csv`: one row per catalog paper with bibliographic identifiers and method category.",
        "- `edges.csv`: directed `source cites target` relationships within the catalog.",
        "- `network.graphml`: the same graph for Gephi, Cytoscape, and NetworkX.",
        "- `network.gexf`: a styled, pre-positioned view for Gephi and Gephi Lite.",
        "- `network.json`: the styled graph consumed by the project web viewer.",
        "- `network.cx`: an NDEx-compatible CX export (built with `scripts/build_ndex_cx.py`).",
        "- `stats.json`: machine-readable scope and validation statistics.",
        "- `SHA256SUMS`: integrity hashes for the release files.",
        "",
        "## Scope notes",
        "",
        "The graph contains machine-screened records and should not be treated as a",
        "manually verified systematic-review inclusion set. Self-loops caused by",
        f"version/identifier reconciliation were excluded ({stats['self_loops_removed']:,} in this snapshot).",
        "Edge discovery is limited",
        "by the coverage and update timing of the upstream scholarly indexes.",
        "",
    ])


def _write_checksums(output_dir: Path, filenames: list[str]) -> None:
    lines = []
    for filename in filenames:
        digest = hashlib.sha256((output_dir / filename).read_bytes()).hexdigest()
        lines.append(f"{digest}  {filename}")
    (output_dir / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_public_graph(
    client: Client,
    edge_path: Path,
    output_dir: Path,
    *,
    version: str = "v1",
) -> dict[str, Any]:
    """Write a versioned, catalog-only citation graph and return its statistics."""
    groups = collect_papers(client)
    papers_by_id = {
        paper.canonical_id: paper
        for category in CATEGORIES
        for paper in groups[category]
    }
    papers = [papers_by_id[paper_id] for paper_id in sorted(papers_by_id)]
    node_ids = set(papers_by_id)
    edges, self_loops = _read_induced_edges(edge_path, node_ids)
    incident = {node_id for edge in edges for node_id in edge}
    category_counts = Counter(paper.category for paper in papers)
    stats: dict[str, Any] = {
        "version": version,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scope": "catalog-induced citation graph",
        "nodes": len(papers),
        "edges": len(edges),
        "nodes_with_internal_edge": len(incident),
        "isolated_nodes": len(node_ids - incident),
        "self_loops_removed": self_loops,
        "category_counts": {
            category: category_counts[category] for category in CATEGORIES
        },
        "components": _component_stats(node_ids, edges),
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    readme = output_dir / "README.md"
    if readme.exists() and not readme.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
        raise FileExistsError(f"refusing to overwrite a hand-edited file: {readme}")
    _write_nodes_csv(output_dir / "nodes.csv", papers)
    _write_edges_csv(output_dir / "edges.csv", edges)
    _write_graphml(output_dir / "network.graphml", papers, edges)
    (output_dir / "stats.json").write_text(
        json.dumps(stats, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    readme.write_text(_render_readme(version, stats), encoding="utf-8")
    _write_checksums(output_dir, ["nodes.csv", "edges.csv", "network.graphml", "stats.json", "README.md"])
    return stats
